media_riddle_marketplace.settings:
  type: config_object
  label: 'Media riddle settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for thumbnails'

media.source.riddle_marketplace:
  label: 'Riddle type configuration'
  type: media.source.field_aware
